M48
; DRILL file {KiCad 6.0.2+dfsg-1} date jue 13 feb 2025 14:12:00
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2025-02-13T14:12:00+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,6.0.2+dfsg-1
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
INCH
; #@! TA.AperFunction,Plated,PTH,ViaDrill
T1C0.0157
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T2C0.0276
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T3C0.0315
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T4C0.0354
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T5C0.0394
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T6C0.0630
%
G90
G05
T1
X6.34Y-4.82
T2
X5.56Y-4.47
X5.66Y-4.37
X5.66Y-4.57
T3
X5.72Y-4.7914
X5.72Y-4.941
X7.7Y-4.3214
X7.7Y-4.471
T4
X5.23Y-4.32
X5.23Y-4.82
T5
X5.9298Y-5.05
X6.0298Y-5.05
X6.1298Y-5.05
X6.2298Y-5.05
X6.3298Y-5.05
T6
X6.54Y-4.2506
X6.54Y-4.9294
T0
M30
