M48
; DRILL file {KiCad 6.0.2+dfsg-1} date jue 13 feb 2025 13:53:13
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2025-02-13T13:53:13+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,6.0.2+dfsg-1
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
INCH
; #@! TA.AperFunction,Plated,PTH,ViaDrill
T1C0.0157
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T2C0.0394
%
G90
G05
T1
X5.72Y-3.87
X6.04Y-3.79
T2
X5.6Y-4.08
X5.7Y-4.08
X5.8Y-4.08
X5.9Y-4.08
X6.0Y-4.08
X6.1Y-4.08
T0
M30
